<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1533433488278" stop="1533433488544">
  <name>scripts</name>
  <labels/>
  <test-cases>
    <test-case start="1533433488278" status="passed" stop="1533433488287">
      <name>hello.test_a</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="2364-MainThread"/>
        <label name="host" value="admin-PC"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1533433488289" status="failed" stop="1533433488544">
      <name>hello.test_b</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>def test_b():
        print("-------&gt;test_b")
&gt;       assert 0 # 断言失败
E       assert 0

scripts\hello.py:8: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="2364-MainThread"/>
        <label name="host" value="admin-PC"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
